moneta/repository/urls.py
from django.conf.urls import include, url
from moneta.repository import views


def get_patterns():
    from moneta.repositories.base import RepositoryModelsClasses
    pattern_list_ = []
    for name, model in RepositoryModelsClasses().get_models().items():
        pattern_list_.append(url(r'^p/%s/' % name, (model.public_urls, name, name)))
    pattern_list_.append(url(r'^p/$', views.public_check, name='public_check'))
    for name, model in RepositoryModelsClasses().get_models().items():
        pattern_list_.append(url(r'^a/%s/' % name, (model.urls, 'auth-' + name, 'auth-' + name)))
        pattern_list_.append(url(r'^b/%s/' % name, (model.public_urls, 'authb-' + name, 'authb-' + name)))
    pattern_list_.append(url(r'^a/$', views.private_check, name='private_check_a'))
    pattern_list_.append(url(r'^b/$', views.private_check, name='private_check_b'))
    return pattern_list_


name_set = set()
urlpatterns = get_patterns()
app_name = 'repository'

moneta/urls.py
from django.conf.urls import url
from moneta.views import public_check, index, check, add_element, add_element_post, add_element_signature, \
    get_signature, modify_repository, delete_repository, delete_element, search_package, compare_states, private_check, \
    test_upload, get_file_p, get_checksum_p, get_signature_p, get_file, get_checksum, show_file


__author__ = 'flanker'

urlpatterns = [
    url(r'^p/$', public_check, name='public_check'),
    url(r'^p/get/(?P<eid>\d+)/(?P<name>.*)$', get_file_p, name='get_file_p'),
    url(r'^p/check/(?P<eid>\d+)/(?P<value>sha1|sha256|md5)$', get_checksum_p, name='get_checksum_p'),
    url(r'^p/signature/(?P<eid>\d+)/(?P<sid>\d+)/$', get_signature_p, name='get_signature_p'),
    url(r'^a/get/(?P<eid>\d+)/(?P<name>.*)$', get_file, name='get_file'),
    url(r'^a/check/(?P<eid>\d+)/(?P<value>sha1|sha256|md5)$', get_checksum, name='get_checksum'),
    url(r'^a/file/(?P<eid>\d+)/$', show_file, name='show_file'),
    url(r'^a/add_package/(?P<rid>\d+)/$', add_element, name='add_element'),
    url(r'^a/post/(?P<rid>\d+)/$', add_element_post, name='add_element_post'),
    url(r'^a/sign/(?P<rid>\d+)/$', add_element_signature, name='add_element_signature'),
    url(r'^a/signature/(?P<eid>\d+)/(?P<sid>\d+)/$', get_signature, name='get_signature'),
    url(r'^a/modify/(?P<rid>\d+)/$', modify_repository, name='modify_repository'),
    url(r'^a/delete/(?P<rid>\d+)/$', delete_repository, name='delete_repository'),
    url(r'^a/delete/(?P<rid>\d+)/(?P<eid>\d+)/$', delete_element, name='delete_element'),
    url(r'^a/search/(?P<rid>\d+)/$', search_package, name='search_package'),
    url(r'^a/compare/(?P<rid>\d+)/$', compare_states, name='compare_states'),
    url(r'^a/index/$', index, name='index'),
    url(r'^a/$', private_check, name='private_check'),
    url(r'^a/check/$', check, name='check'),
    url(r'^test/$', test_upload, name='test_upload'),

]
app_name = 'moneta'

moneta/repositories/models.py
__author__ = 'flanker'

moneta/repository/models.py
import logging
import os
import uuid
import functools

from django.conf import settings
from django.contrib.auth.models import Group, Permission
from django.urls import reverse
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_delete, post_migrate
from django.dispatch import receiver
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _, gettext

from moneta.exceptions import InvalidRepositoryException
from moneta.repository.storages import BaseStorage
from moneta.utils import normalize_str, remove, import_path

__author__ = 'flanker'

logger = logging.getLogger('moneta.files')

ARCHIVE_FILTER_CALLABLES = None
STORAGES = {}


@functools.lru_cache()
def storage(name) -> BaseStorage:
    kwargs = settings.STORAGES.get(name, settings.STORAGES['default'])
    cls = import_path(kwargs['ENGINE'])
    return cls(**kwargs)


@functools.lru_cache()
def archive_filters():
    """
    Check if archive filters set in settings are loaded. If not, load them.

    :return: a list of callable to call on new archives files.
    """
    result = []
    for middleware_path in settings.ARCHIVE_FILTERS:
        result.append(import_path(middleware_path))
    return result


class BaseModel(models.Model):
    name = models.CharField(_('Name'), max_length=100, blank=False, db_index=True)
    slug = models.SlugField(_('Slug'), max_length=100, blank=False, db_index=True)
    creation = models.DateTimeField(_('Creation date'), db_index=True, auto_now_add=True)
    modification = models.DateTimeField(_('Modification date'), db_index=True, auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Author'), db_index=True, blank=True, null=True,
                               on_delete=models.SET_NULL)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Repository(BaseModel):
    archive_type = models.CharField(_('Repository type'), db_index=True, max_length=100)
    on_index = models.BooleanField(_('Display on public index?'), db_index=True, default=True, blank=True)
    is_private = models.BooleanField(_('Should readers be authenticated?'), db_index=True, default=False, blank=True)
    admin_group = models.ManyToManyField(Group, verbose_name=_('Admin groups'), db_index=True, blank=True,
                                         related_name='repository_admin')
    reader_group = models.ManyToManyField(Group, verbose_name=_('Readers groups'), db_index=True, blank=True,
                                          related_name='repository_reader')

    class Meta:
        verbose_name = 'repository'
        verbose_name_plural = 'repositories'

    def get_model(self):
        from moneta.repositories.base import RepositoryModelsClasses
        return RepositoryModelsClasses.get_model(self.archive_type)

    def get_absolute_url(self):
        return reverse('repository:%s:index' % self.archive_type, kwargs={'rid': self.id})

    @staticmethod
    def index_queryset(request):
        user = request.user
        if user.is_anonymous:
            return Repository.objects.filter(Q(on_index=True) | Q(author=None)).distinct()
        return Repository.objects.filter(Q(on_index=True) | Q(author=user)).distinct()

    @staticmethod
    def upload_queryset(request):
        user = request.user
        if user.is_anonymous:
            return Repository.objects.filter(author=None)
        elif user.is_superuser:
            return Repository.objects.all()
        return Repository.objects.filter(Q(admin_group=user.groups.all()) | Q(author=user)).distinct()

    @staticmethod
    def admin_queryset(request):
        user = request.user
        if user.is_anonymous:
            return Repository.objects.filter(author=None)
        elif user.is_superuser:
            return Repository.objects.all()
        return Repository.objects.filter(author=user)

    @staticmethod
    def reader_queryset(request):
        user = request.user
        if user.is_anonymous:
            return Repository.objects.filter(Q(is_private=False) | Q(author=None)).distinct()
        return Repository.objects.filter(Q(is_private=False) | Q(author=user) | Q(reader_group__in=user.groups.all())
                                         | Q(admin_group__in=user.groups.all())).distinct()

    def upload_allowed(self, request):
        return self.upload_queryset(request).filter(id=self.id)[0:1].count() > 0

    def admin_allowed(self, request):
        return self.admin_queryset(request).filter(id=self.id)[0:1].count() > 0

    def reader_allowed(self, request):
        user = request.user
        if user.is_anonymous:
            return not self.is_private
        return not self.is_private or self.author == user or \
               (not {x.id for x in user.groups.all()}.isdisjoint({x.id for x in self.reader_group.all()})) or \
               (not {x.id for x in user.groups.all()}.isdisjoint({x.id for x in self.admin_group.all()}))


class ArchiveState(BaseModel):
    repository = models.ForeignKey(Repository, verbose_name=_('Repository'), db_index=True,
                                   on_delete=models.CASCADE)


class Element(BaseModel):
    official_link = models.URLField(_('URL to the web page'), max_length=255, blank=True)
    short_description = models.CharField(_('Short description'), max_length=500, blank=True)
    long_description = models.TextField(_('Long description'), blank=True)
    states = models.ManyToManyField(ArchiveState, verbose_name=_('Archive states'), db_index=True)
    repository = models.ForeignKey(Repository, verbose_name=_('Repository'), db_index=True,
                                   on_delete=models.CASCADE)
    full_name = models.CharField(_('Complete name'), max_length=255, blank=True, db_index=True)
    full_name_normalized = models.CharField(_('Normalized complete name'), max_length=255, blank=True, db_index=True,
                                            help_text=_("Complete name without special chars nor accents"))
    archive = models.CharField(_('Archive'), db_index=True, blank=True, default='', max_length=255)
    version = models.CharField(_('Version'), db_index=True, blank=True, default='', max_length=255)
    filename = models.CharField(_('filename'), max_length=255, blank=True, db_index=True, default='',
                                help_text=_('Automatically generated on creation'))
    uuid = models.CharField(_('UUID'), db_index=True, max_length=40, blank=True,
                            help_text=_('Unique identifier, automatically generated on first save'))
    md5 = models.CharField(_('MD5 sum'), max_length=120, blank=True, db_index=True, default='',
                           help_text=_('Automatically generated on creation'))
    sha1 = models.CharField(_('SHA1 sum'), max_length=120, blank=True, db_index=True, default='',
                            help_text=_('Automatically generated on creation'))
    sha256 = models.CharField(_('SHA256 sum'), max_length=120, blank=True, db_index=True, default='',
                              help_text=_('Automatically generated on creation'))
    filesize = models.IntegerField(_('File size'), default=0, blank=True, db_index=True,
                                   help_text=_('Automatically generated on creation'))
    extension = models.CharField(_('File extension'), db_index=True, max_length=20, blank=True, default='',
                                 help_text=_('Automatically generated on creation'))
    mimetype = models.CharField(_('MIME type'), db_index=True, max_length=40, blank=True, default='',
                                help_text=_('Guessed on creation'))
    archive_file = models.FileField(_('Archive file'), blank=True, default='', null=True,
                                    upload_to=settings.UPLOAD_ROOT, help_text=_('Any text, binary or archive file.'))
    archive_key = models.CharField(_('Original file'), blank=True, max_length=255, db_index=True, default='')
    uncompressed_key = models.CharField(_('Stored path'), blank=True, max_length=255, db_index=True, default='')
    extra_data = models.TextField(_('Extra repo data'), blank=True, default='')

    class Meta:
        verbose_name = _('file')
        verbose_name_plural = _('files')

    @staticmethod
    def reader_queryset(request):
        return Element.objects.filter(repository__in=Repository.reader_queryset(request))

    def remove_file(self):
        if self.archive_key:
            storage(settings.STORAGE_ARCHIVE).delete(self.archive_key)
            self.archive_key = None
        if self.uncompressed_key:
            storage(settings.STORAGE_UNCOMPRESSED).delete(self.uncompressed_key)
            self.uncompressed_key = None

    def save(self, *args, **kwargs):
        """
        :param args:
        :param kwargs:
        :return:
        """
        if not self.uuid:
            self.uuid = str(uuid.uuid1())
        if (self.archive_file is not None) and self.archive_file.name:  # a new file is uploaded
            uploaded_file = self.archive_file
            # noinspection PyBroadException
            try:
                uploaded_file.open('rb')
                filename = os.path.basename(uploaded_file.name)
                self.set_file(uploaded_file.file, filename)
            except Exception:
                logger.error(gettext('Unable to add the archive file'), exc_info=True)
            exceptions = []
            cls = self.repository.get_model()
            if not cls.is_file_valid(uploaded_file):
                exceptions.append(str(self.repository))
            else:
                cls.update_element(self)
            if len(exceptions) == 1:
                raise InvalidRepositoryException(

moneta/repository/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.utils.text import slugify
from django.utils.translation import gettext as _
import functools
from moneta.repository.models import Repository, ElementSignature

__author__ = 'flanker'


def repo_name_validator(value):
    if Repository.objects.filter(slug=slugify(value)).count() > 0:
        raise ValidationError(_('This repository already exists.'))


@functools.lru_cache()
def get_repository_form():
    from moneta.repositories.base import RepositoryModelsClasses

    class RepositoryForm(forms.Form):
        name = forms.CharField(max_length=80, label=_('Repository name'), validators=[repo_name_validator])
        archive_type = forms.ChoiceField(label=_('Type of archives'), choices=RepositoryModelsClasses())
        on_index = forms.BooleanField(label=_('Add on public index?'), initial=True, required=False)
        is_private = forms.BooleanField(label=_('Authentication required?'), initial=False, required=False, widget=forms.HiddenInput())
        states = forms.CharField(label=_('Possible states for archives'), initial='qualif prod',
                                 help_text=_('Please separate values by spaces'),
                                 validators=[RegexValidator('\w+(\s\w)*')])
        admin_group = forms.ModelMultipleChoiceField(Group.objects.all(), label=_('Groups allowed to upload packages'),
                                                     required=False)
        reader_group = forms.ModelMultipleChoiceField(Group.objects.all(), widget=forms.HiddenInput(),
                                                      label=_('Groups allowed to download packages'),
                                                      help_text=_('Only if downloads require authentication'), required=False)

    return RepositoryForm


CONFIRM_PHRASE = _('yes, I want to delete this element.')


def confirm_phrase(value):
    if value != CONFIRM_PHRASE:
        raise ValidationError(_('You must confirm the deletion.'))


class DeleteRepositoryForm(forms.Form):

    confirm = forms.CharField(max_length=80, label=_('Please enter “%(confirm)s”') % {'confirm': CONFIRM_PHRASE},
                              validators=[confirm_phrase])


class RepositoryUpdateForm(forms.Form):
    on_index = forms.BooleanField(label=_('Display on index for everybody?'), initial=True, required=False)
    is_private = forms.BooleanField(label=_('Must downloads be authenticated?'), initial=False, required=False, widget=forms.HiddenInput())
    states = forms.CharField(label=_('Possible states'), initial='dev qualif prod',
                             help_text=_('Please separate values by spaces'),
                             validators=[RegexValidator('\w+(\s\w)*')])
    admin_group = forms.ModelMultipleChoiceField(Group.objects.all(), label=_('Groups allowed to upload'),
                                                 required=False)
    # reader_group = forms.ModelMultipleChoiceField(Group.objects.all(), widget=forms.HiddenInput(),
    #                                               help_text=_('Only if downloads are authenticated'),
    #                                               label=_('Groups allowed to download packages'), required=False)


class SignatureForm(forms.Form):
    sha256 = forms.CharField(label=_('SHA256'), max_length=255, validators=[RegexValidator(r'\w{64}')])
    method = forms.ChoiceField(label=_('Method'), choices=ElementSignature.METHODS)

moneta/repository/views.py
from django.contrib import messages
from django.template.response import TemplateResponse
from django.utils.translation import gettext_lazy as _


def public_check(request):
    messages.success(request, _('You can access to this page.'))
    return TemplateResponse(request, 'core/empty.html', {})


def private_check(request):
    if request.user.is_anonymous:
        messages.error(request, _('You are not authenticated.'))
    else:
        messages.success(request, _('You can access to this page and you are authenticated.'))
    return TemplateResponse(request, 'core/empty.html', {})

moneta/repositories/templates/repositories/maven3/browse.html
{% extends "moneta/base_package.html" %}{% load staticfiles i18n moneta %}
{% block bootstrap3_title %}{% blocktrans %}Repository {{ repo }}{% endblocktrans %}{% if state_slug %}/{{ state_slug }}{% endif %}{% endblock %}

{% block repo_content %}
    <h1><a href="{{ repo.get_absolute_url }}">{% blocktrans %}Repository {{ repo }}{% endblocktrans %}{% if state_slug %}/{{ state_slug }}{% endif %}</a></h1>
    <ol class="breadcrumb">
    {% for bread_crumb in bread_crumbs %}
        <li {% if forloop.last %}class="active"{% endif %}><a href="{{ bread_crumb.1 }}">{{ bread_crumb.0 }}</a></li>
    {% endfor %}
    </ol>
    <p>{% blocktrans %}Available files in <strong>{{ repo }}/{{ request_path }}</strong>: {% endblocktrans %}
        <span class="badge">{{ element_count }}</span></p>
    <ul class="list-unstyled">
        {% for path in paths %}
            <li><a href="{{ path.1 }}">{{ path.0 }}</a>
                {% if path.2 %}<a href="{% url 'moneta:show_file' path.2 %}" class="btn btn-success btn-xs">{% trans 'More infos…' %}</a>{% endif %}

            </li>
            {% empty %}
            <li>{% trans 'No available package' %}</li>
        {% endfor %}
    </ul>
{% endblock %}

moneta/repositories/templates/repositories/maven3/folder_index.html
{% extends "moneta/base_package.html" %}{% load staticfiles i18n %}
{% block bootstrap3_title %}{% blocktrans %}Repository {{ repo }}{% endblocktrans %}{% if state_slug %}/{{ state_slug }}{% endif %}{% endblock %}

{% block repo_content %}
    <h1><a href="{{ repo.get_absolute_url }}">{% blocktrans %}Repository {{ repo }}/{{ state }}{% endblocktrans %}</a></h1>
    <p>{% blocktrans %}Available packages in <strong>{{ repo }}/{{ state }}/{{ folder }}</strong> {% endblocktrans %}
        <span class="badge">{{ element_count }}</span></p>
    <ul class="nav nav-pills">
        {% for element in elements %}
            <li>{% include 'moneta/element.html' %}</li>
        {% endfor %}
    </ul>
{% endblock %}

moneta/repositories/templates/repositories/maven3/index.html
{% extends "moneta/base_package.html" %}{% load staticfiles i18n moneta %}
{% block base_repo_urls %}
    <div class="btn-group">
        <a class="btn btn-sm btn-default" href="{{ repo.get_absolute_url }}">{% trans 'usage' %}</a>
        <a class="btn btn-sm btn-default"
           href="{% url 'moneta:search_package' rid=repo.id %}">{% trans 'browse repository' %}</a>
        <a class="btn btn-sm btn-default"
           href="{% url 'moneta:compare_states' rid=repo.id %}">{% trans 'check' %}</a>
        {% if admin_allowed %}
            <a class="btn btn-sm btn-default"
               href="{% url 'moneta:modify_repository' rid=repo.id %}">{% trans 'modify repository' %}</a>
            <a class="btn btn-sm btn-danger"
               href="{% url 'moneta:delete_repository' rid=repo.id %}">{% trans 'delete repository' %}</a>
        {% endif %}
    </div>{% endblock %}

{% block repo_content %}
                <h2>{% trans 'Maven settings' %}</h2>
        <ul class="nav nav-tabs">
            {% for state_info in state_infos %}
            <li {% if forloop.first %}class="active"{% endif %}><a href="#state_{{ state_info.0 }}" data-toggle="tab">{{ state_info.2 }}</a></li>
            {% endfor %}
        </ul>
        <div class="tab-content">
            {% for state_info in state_infos %}
                <div class="tab-pane {% if forloop.first %}active{% endif %}" id="state_{{ state_info.0 }}">
                <p>{% trans 'Add the following repositories to your pom.xml in the repositories section:' %}</p>
                    <pre>{{ state_info.1 }}</pre>
                {% if upload_allowed %}
                    <h2>{% trans 'Add a package' %}</h2>
            <p>{% trans 'You can add packages by specifying archive (groupId.artifactId, name of the package) and version:' %}</p>
                <pre>FILENAME=filename-version.XXX
ARCHIVE=$groupId.$artifactId
VERSION=$version
{% curl %} --data-binary @$FILENAME {{ absolute_url }}{% url 'moneta:add_element_post' rid=repo.id %}\?filename=$FILENAME\&archive=$ARCHIVE\&version=$VERSION{% for state in state_info.3 %}\&amp;states={{ state }}{% endfor %}</pre>{% endif %}
                </div>
            {% endfor %}
        </div>
    {% include 'moneta/add_signature.html' %}
{% endblock %}